<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>rm_bringup</name>
  <version>1.7.0</version>
  <description>TODO: Package description</description>
  <maintainer email="rm@todo.todo">rm</maintainer>
  <license>TODO: License declaration</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>rm_control</exec_depend>
  <exec_depend>rm_description</exec_depend>
  <exec_depend>rm_driver</exec_depend>
  <exec_depend>rm_gazebo</exec_depend>
  <exec_depend>rm_63_config</exec_depend>
  <exec_depend>rm_65_config</exec_depend>
  <exec_depend>rm_75_config</exec_depend>
  <exec_depend>rm_eco62_config</exec_depend>
  <exec_depend>rm_eco63_config</exec_depend>
  <exec_depend>rm_eco65_config</exec_depend>
  <exec_depend>rm_gen72_config</exec_depend>
  <exec_depend>rm_rx75_config</exec_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
